import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
  <div style={{ display: "flex", minHeight: "100vh" }}>
    
    {/* Sidebar */}
    <aside
      style={{
        width: "220px",
        background: "#111",
        color: "white",
        padding: "20px",
      }}
    >
      <h2 style={{ fontWeight: 700, marginBottom: 20 }}>AI CRM</h2>

      <nav style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        <a href="/">Dashboard</a>
        <a href="/deals">Deals</a>
        <a href="/tasks">Tasks</a>
      </nav>
    </aside>

    {/* Main content area */}
    <main style={{ flex: 1, padding: "24px" }}>
      {children}
    </main>

  </div>
</body>
    </html>
  );
}
